server:
  port: 0

spring:
  application:
    name: my-first-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      name: jsp
      profile: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    root: info
    com:
      example:
        demo: info